/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AtividadeTime;

public class App {
    
    public static void main(String[] args) {
     
       
Equipe equipe_bugatti = new Equipe();
Equipe equipe_kawazaki = new Equipe();
Equipe equipe_honda = new Equipe();
       
        equipe_bugatti.p1 = new Piloto("Joao", 45);
        equipe_bugatti.p2 = new Piloto("Felipe", 19);
        
        equipe_bugatti.m1 = new Moto(new Motor_Bugatti());
        equipe_bugatti.m2 = new Moto(new Motor_Bugatti());      
        
        equipe_bugatti.tec = new Tecnico("Ricardo");
        
        
                equipe_honda.p1 = new Piloto("Leo", 45);
                equipe_honda.p2 = new Piloto("Gustae", 19);

                equipe_honda.m1 = new Moto(new Motor_honda());
                equipe_honda.m2 = new Moto(new Motor_honda());      

                equipe_honda.tec = new Tecnico("Galvao Boeno");
        
                            equipe_kawazaki.p1 = new Piloto("Cleber", 45);
                            equipe_kawazaki.p2 = new Piloto("Jonilson", 19);

                            equipe_kawazaki.m1 = new Moto(new Motor_Kawazaki());
                            equipe_kawazaki.m2 = new Moto(new Motor_Kawazaki());      

                            equipe_kawazaki.tec = new Tecnico("Enilson");
    
        System.out.println(equipe_bugatti.m1.acelerar());
        
        System.out.println(equipe_honda.m1.acelerar());
          
        System.out.println(equipe_kawazaki.m2.acelerar());
                            
    }
}
